- xml/deployment_iscsi.xml
This PR removes a duplicated "tpg_login_timeout" property on lrbd example. This fix has already been applied on [lrbd wiki page](https://github.com/SUSE/lrbd/wiki/Home/_history) (see revision a33e24e)
> Removed duplicated "tpg_login_timeout" property on lrbd example

- xml/deployment_iscsi.xml
This PR removes double quotes from "backstore_max_unmap_lba_count" property for consistency with other lrbd properties in this documentation.
> Removed double quotes from "backstore_max_unmap_lba_count" lrbd property

- xml/admin_operating_pools.xml
Only bluestore_* parameters are currently documented. Avoid confusion with other compression settings, precedence, etc.
> Added bluestore_ prefix to compression, BSC#1053247

- xml/deployment_iscsi.xml
If the tcmu-runner service is not running, the first step described on "**9.5.2 Configuration and Deployment**" will fail because tcmu-runner RBD handler requires this service to be running.
For this reason, this PR moves the service status check from the bottom of the section "**9.5.2 Configuration and Deployment**" to the bottom of "**9.5.1 Installation**" section.
> Move tcmu-runner service status check to installation section

- xml/admin_saltcluster.xml
* To remove an OSD, DeepSea safety has to be disengaged
* The remove needs the OSD_ID in digits without the leading "osd."
> Change Removing OSD

- xml/deployment_cifs.xml
- xml/deployment_ganesha.xml
- "Samba" instead of "SAMBA".
- The warning applies to native CephFS clients as well as Samba and NFS.
> Clarify cross protocol access warning, fate#326335

- xml/admin_saltcluster.xml
When accepting keys with salt-key it is either `salt-key -a` or `salt-key --accept`
The document said `salt-key --a` and that throws a `salt-key: error: ambiguous option: --a`
I do think the long options are better suitable for documentation.
> Typo when accepting salt-key

- xml/admin_rbd.xml
> RBD 'exclusive-lock' and 'stripingv2' are supported by iSCSI

- xml/admin_install_salt.xml
Disks with GPT partition tables cannot be used with ceph-volume.
> Remove GPT partition table step

- xml/admin_operating_monitor.xml
Add documentation how to use install and configure the Prometheus Alertmanager SNMP trap receiver (https://github.com/SUSE/prometheus-webhook-snmp).
Signed-off-by: Volker Theile <vtheile@suse.com>
> Prometheus Alertmanager SNMP trap receiver docu

- xml/admin_ceph_tips.xml
As per the discussion on ses-users, /dev/sdd should be changed to just sdd.
> Remove /dev from disk device names

- xml/deployment_cifs.xml
NT4 style domains are ancient. Only AD domain joins should be covered.
> samba: don't document NT4 domain joins

- xml/copyright_suse_storage_cc.xml
Ensuring documents are only licensed under CC-BY-SA-4.0 and copyright is attributed to SUSE. Previously, copyright was attributed to both Red Hat and SUSE. This also removes the Red Hat license. CC-BY... is the appropriate license used for Ceph upstream.
> Removing Red Hat from copyright and licensing

- xml/admin_ceph_upgrade.xml
- xml/admin_install_salt.xml
- xml/manager_modules.xml
Adding telemetry module docs. Tim Serong (bug reporter)
wanted the docs in the mgr modules section and linked
to the appropriate deploy and upgrade sections.
Backport: SES6
> Adding telemetry module docs (BSC#1150907)

- xml/book_storage_admin.xml
- xml/book_storage_deployment.xml
- xml/ses_glossary.xml
As per the title
Removed the <part>...</part>
Change the title within the glossary itself to "Glossary" -- previously I had changed this to "Terms Used in this Manual" so that the Contents pages did not say:
Glossary:
...  Glossary
> Remove the <part> around Glossary; revert its title (BSC#1154581)

- xml/admin_install_salt.xml
salt-call --local key.finger only works if the local salt-minion
can talk to a salt master. This note during step 10 clarifies
this.
> Adding a note to clarify salt-minion fingerprint (BSC#1154346)

- xml/admin_ceph_erasure.xml
The default for min_size on EC pools is k+1.
As changed here: https://github.com/ceph/ceph/pull/8008
> Added min_size for EC pools (BSC#1153481)

- xml/admin_install_salt.xml
The initial step 5 did not clarify that you are required to run
the following commands to initiate the discovery phase. This
addition syncs the instructions with step 7, and makes it clear
to the user they have to run these commands.
> Add "run discovery stage command" instruction (BSC#1154437)

- xml/manager_modules.xml
Updating the tip section "Movable Fraction of Placement Groups (PGs)"
as the command displayed was based on the upstream doc for
mimic. This corrects that command to the nautilus command.
> Updating throttling command for nautilus (BSC#1154602)

- xml/admin_install_salt.xml
The original example confused the reader by mentioning "bytes".
5G is not bytes, and the recommendation follows the example
upstream. See: https://github.com/SUSE/DeepSea/wiki/Drive-Groups#specification
> Removing "bytes" confusion from '5G' example (BSC#1153582)

- xml/deployment_cephfs.xml
Change "MDS nodes" to "MON nodes" in 11.1  Supported CephFS Scenarios and Guidance §
> Backporting BSC #1135168 fix to SES 5.5

- xml/admin_install_salt.xml
Prior to running DeepSea stage 0, you need to apply the
commands to each of the salt minions that will become ceph
monitors. This PR adds both commands to step 3.
> Added salt minion command for btrfs sub-volume creation (BSC#1154435)

- xml/admin_ceph_gateway.xml
- xml/admin_docupdates.xml
- xml/ses_glossary.xml
Archive sync modul enables creating a new OGW zone for collecting history of OGW objects' versions.
- Created a new section describing what archive modul is and how to create its zone.
- updated docupdates section
- extended glossary for 1 term
> Document OGW archive sync module zone (jsc#ses 380)

- xml/admin_ceph_erasure.xml
The original pull request https://github.com/SUSE/doc-ses/pull/111/files
updated with the default min_size for EC pools.
This PR includes the recommended size from SUSE.
> Adding SUSE recommendation for erasure coded pools (BSC#1153481)

- xml/maintenance_updates_admin.xml
- xml/maintenance_updates_deploy.xml
Replaced &lt;sect1>'s with &lt;bridgehead>'s so that the section numbers are not numbered.
The numbering caused confusion with the ceph version numbers in the titles because one went up whil the other down
> Remove section numbering in Ceph updates chapter (bsc#1151881)

- xml/admin_ceph_upgrade.xml
Found several text formatting flaws in the ntp to chrony migration section.
This PR fixes them.
> Fixed minor formatting issues in ntp to chrony migration section

- xml/deployment_cephfs.xml
As of SES5, we support multiple active MDS in CephFS. This
documentation ensures that is up-to-date.
Backport: SES5
> Adding documented support for multiple active MDS daemons (BSC#1154562)

- xml/admin_ceph_upgrade.xml
Bluestore is the default for SES 5.x and 6, however for customers
performing any upgrade path, they may not have completed this
requirement when upgrading from SES 4 to SES 5. This PR
includes the content from SES 5.5 docs.
> Adding filestore to bluestore upgrade content (BSC#1141175)

- xml/deployment_hwrecommend.xml
- xml/entity-decl.ent
SES has supported ARM architecture since SES 4. Going forward
we want to ensure this is documented for customers. There is
no major difference between the two architectures (x86 and ARM)
but it is important to have documented.
> Adding new intro chap for Arm architecture (BSC#1154813)

- xml/admin_gui_oa.xml
By default prometheus only stores 15 days. These instructions
allow the user to alter this env.
> Add instruction for how to increase prometheus data store (BSC#1123032)

- xml/admin_ceph_upgrade.xml
- xml/deployment_docupdates.xml
After admin node is upgraded, you can watch all cluster nodes' status. The `upgrade.status`
runner replaces the old `status.report`
> Added a tip on monitoring cluster nodes' status during upgrade (bsc#1154568)

- xml/admin_nfsganesha.xml
this updates the link to the current correct URI.
> Broken link to the NFS chapter of the SLES15-SP1 admin guide

- xml/admin_ceph_cephfs.xml
The "ceph mds set" does not exist in SES6, updates the
commit to "ceph fs set cephfs"
> Updating the "ceph mds set" command (BSC#1157885)

- xml/admin_docupdates.xml
- xml/ceph_maintenance_updates.xml
- xml/deployment_docupdates.xml
SES supports new Ceph Nautilus version, this update lists new features in that release.
As a part of this update, i also simplified docupdates sections by joining bugfixes and general updates.
> Added release notes for Ceph 14.2.5 (bsc#1158944)

- xml/admin_ceph_upgrade.xml
When not using repository providers, the upgrade may require enabling additional channels/modules manually. This update adds a tip with that information.
> Additional software channels (bsc#1158106)

- xml/deployment_docupdates.xml
- xml/deployment_hwrecommend.xml
The general paragraph about network recommendations was a bit vague and did not refer
to a SLE section which explains how to set bonding devices. This PR amends that.
> Made network recommendations more specific (bsc#1156631)

- xml/admin_saltcluster.xml
The 'salt osd.retain' command for updating Salt grains after OSD recovery is obsoleted in SES6. This update suggest alternative way to remove stale grains.
> 'salt osd.retain' is obsoleted (bsc#1160219)

- xml/admin_ceph_cephfs.xml
- xml/admin_ceph_datamgm.xml
- xml/admin_ceph_upgrade.xml
- xml/admin_gui_dashboard.xml
- xml/admin_install_salt.xml
- xml/admin_saltcluster.xml
- xml/ceph_maintenance_updates.xml
- xml/ceph_prompts.xml
- xml/deployment_cifs.xml
The localization team pointed me to several string in SES6 manuals that were unclear and could be said in a simple language. This update offer more legible alternatives.
> Updated unclear strings with understandable alternatives

- xml/admin_ceph_gateway.xml
- xml/admin_ceph_iscsi.xml
- xml/admin_ceph_libvirt.xml
- xml/deployment_hwrecommend.xml
- xml/deployment_iscsi.xml
SES 6 supports both x86 and arm arch, however a lot of commands
specifically poin to x86. This patch offers a suggestion on how to
change this.
> Removing specific instances of x86 in favor of <replaceable> (BSC#1155012)

- xml/admin_ceph_troubleshooting.xml
- xml/admin_install_salt.xml
Deployment section about time synchronization was misleading, this update fixes it and describes how to override the default DeepSea's configuration.
> Overriding default NTP settings (bsc#1160080)

- xml/admin_ceph_upgrade.xml
The `salt-run upgrade.check` runner verifies several points that could prevent the cluster from upgrading correctly. This update inserts this runner before the actual upgrade procedure.
> Run upgrade.check runner to verify upgrade conditions (jsc#SES-356)

- xml/admin_ceph_erasure.xml
- xml/admin_operating_pools.xml
The current list of values that you can set on a pool mixes both replicated and EC pools. This update divides the pool values into three lists corresponding to pool types.
> Aligned list of pool values (bsc#1113674)

- xml/admin_ceph_datamgm.xml
- xml/admin_ceph_gateway.xml
- xml/admin_operating_monitor.xml
- xml/ceph_maintenance_updates.xml
- xml/manager_modules.xml
Small updates to make several snippets more clear as suggested by the localization team.
As an addition, all 'luminous' cases were capitalized to 'Luminous' for consistency.
> Fixed unclear localization strings, round 2

- xml/admin_ceph_upgrade.xml
Several commands had prompts that instructed the admin to run the corresponding commands on an OSD node instead of the Admin node. This update fixes them.
> Prompt fixes in the upgrade chapter (bsc#1161801)

- xml/ceph_maintenance_updates.xml
After discussion with @Martin-Weiss, added a warning about free cluster space when adding replicas. 
This fixes:
https://bugzilla.suse.com/show_bug.cgi?id=1161691
> Add warning about free space when adding replicas (bsc#1161691)

- xml/admin_operating_services.xml
Updated and extended the way and order of nodes during a complete cluster shutdown/start-up.
This update applies to SES6+
> Shutdown and start of the whole cluster (bsc#1126210)

- xml/admin_saltcluster.xml
The 'ceph.maintenance.upgrade' runner is not supported anymore and this update replaces it with two other commands.
> ceph.maintenance.upgrade runner not yet supported (bsc#1158449)

- xml/authors.xml
The authors are different per-release. This should accurately reflect the authors.
Jana has been removed but remains for SES 5.5 0 thoughts?
> Editing authors for SES 6

- xml/admin_rbd.xml
As per:
https://bugzilla.suse.com/show_bug.cgi?id=1114306
Promoted the tip on Ceph user authentication to a new subsection at the start of
§ 12.2 Mounting and Unmounting
Added new material from upstream docs on creating new A/Cs
This is all the material I have access to -- for info on installing additional components I need some more info.
>  Add §s on managing & using Ceph user accounts (bsc#1114306) 

- xml/deployment_iscsi.xml
Username and passwoords for iSCSI CHAP authentication can contain not only letters, but numbers as well. This update extends the list of valid characters.
> CHAP authentication username/password update (bsc#1165729)

- xml/admin_operating_services.xml
This was fixed in master, but apparently was not backported to SES 6.
This fixes that.
> Fixing incorrect command for SES 6 (BSC#1166525)

- xml/admin_monitoring_alerting.xml
"ceph telemetry soff" is not a valid command.  To turn off telemetry, use "ceph telemetry off".  Fixed typo.
> Fix typo in admin_monitoring_alerting.xml: s/soff/off/

- xml/deploy_cephadm.xml
Since https://github.com/ceph/ceph-salt/pull/166, config nodes are lowercase.
Also, since https://github.com/ceph/ceph-salt/pull/113, we now have a new `/containers/registries` config node.
> Convert ceph-salt config nodes to lowercase

- xml/admin_nfsganesha.xml
Backport to SES 6. The name depends on the suse_version macro in rpm
> Fixing ganesha file name - Closes #250

- xml/deploy_cephadm.xml
https://github.com/ceph/ceph-salt/pull/200 will rename `ceph-salt deploy` command to `ceph-salt apply`.
> Rename `ceph-salt deploy` to `ceph-salt apply`

- xml/deploy_cephadm.xml
`/time_server/subnet` exists since https://github.com/ceph/ceph-salt/pull/165
> Add missing ceph-salt '/time_server/subnet' node

- xml/deploy_cephadm.xml
Also removes mention of in-progress operation status (which we don't have)
> Fix typo in `ceph orch status`

- xml/deploy_cephadm.xml
Specifying the admin keyring to the first bootstrap MON is mandotory, therefore changing a 'tip' to 'important'
> Changed 'tip' to 'important' (bsc#1169856)

- xml/deploy_cephadm.xml
Replaced `drive_groups.xml` with `drive_groups.yml` (as it's a YAML file)
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
> deploy_cephadm.xml: fixed typo

- xml/admin_gui_dashboard.xml
Dashboard login credentials can no longer be obtained from DS grain,
this update fixes #300.
NOTE: this PR is failing because it referes XML ID that is not yet merged into 'master'
> Removed old way of getting dashboard credetials (gh#SUSE/doc-ses#300)

- xml/deploy_cephadm.xml
The deployment procedure missed instructions on configuring Dashboard's login credentials.
This update adds such section and fixes #301
> Added section on dashboard credentials (gh#SUSE/doc-ses#301)

- xml/deploy_cephadm.xml
In the example the host `ses-min1.example.com` has been added to role admin:
`ceph-salt config /ceph_cluster/roles/admin add ses-min1.example.com`. But the command `ceph-salt config /ceph_cluster/roles/admin ls` is showing the hostname: `ses-min1.suse.cz` afterwards.
Correct the amount of admin minions too.
> Correct /ceph_cluster/roles/admin ls output

- xml/deploy_cephadm.xml
One needs to specify all minions at once separated by commas when applying Ceph services.
Closes #330
> Specify multiple minions at once for Ceph services (gh#SUSE/doc-ses#330)

- xml/admin_ceph_cephfs.xml
Removing documentation for standby-for options and adding
upstream documentation.
> standby-for options have been deprecated within cephfs (BSC#1171365)

- xml/deploy_cephadm.xml
This update removes the `ceph orch daemon add osd` way of adding OSDs, in favour of the Drivegroups approach
> Removed CLI per host adding OSD (bsc#1172129)

- xml/admin_ceph_gateway.xml
- xml/admin_operating_monitor.xml
- xml/admin_saltcluster.xml
- xml/common_intro_available_doc_i.xml
- xml/deploy_cephadm.xml
- xml/runtime_config.xml
- xml/tuning-ceph-tiered-storage.xml
- xml/tuning-lvmcache.xml
Brings the following chanegs:
- moved 'Adding New Nodes' from Deployment to Admin Guide
-  rewrote 'Removing Nodes'
- rewrote 'Removing OSDs'
- rewrote 'Replacing OSDs'
- updated all affected references so that it all validates
find attached the rendered version - but pay attention only to sections 4.1 to 4.4
[storage-salt-cluster_color_en.pdf](https://github.com/SUSE/doc-ses/files/4791670/storage-salt-cluster_color_en.pdf)
> Updated several Admin Guide sections to SES7

- xml/deploy_cephadm.xml
Since https://github.com/ceph/ceph-salt/pull/262, path has changed from `/containers/registries` to `/containers/registries_conf/registries`.
> Fix ceph-salt registries path

- xml/deploy_cephadm.xml
[deploy-cephadm-day1_color_en.pdf](https://github.com/SUSE/doc-ses/files/4817930/deploy-cephadm-day1_color_en.pdf)
- mentions cache registry and adds a reference to CaaSP ait-gapped section (closes #359 )
- fixes wording (closes #377 )
- removes deafault insecure access example (closes #374)
> Extends section on container registry (gh#359)

- xml/book_storage_admin.xml
- xml/book_storage_deployment.xml
- xml/book_storage_security.xml
- xml/book_storage_troubleshooting.xml
The glossary is currently set before the docuupdates in each of
the guides, but breaks up the appendix lettering. This looks
messy and inconsistent. This change aligns the ordering so that
it no longer breaks up the lettering sequence.
> Moving the glossary to the end Closes#312

- xml/deploy_cephadm.xml
Originally the request was to add umask, but to avoid overcomplication, adding a warning to the export command should ensure individual are aware of the risk.
> Adding warning to ceph-salt export command  - Closes#339

- xml/deploy_cephadm.xml
Better explain the role of ceph-salt in the introduction.
It's no longer necessary to install a Salt Minion on the Master node.
Update the `ls` output of `ceph-salt config`, improved the order of the examples to be less confusing (#357)
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
> deploy_cephadm.xml: various ceph-salt related improvements

- xml/admin_ceph_upgrade.xml
- xml/deployment_ds_custom.xml
Fujistu requested a clarification on the disabling time sync note. See https://bugzilla.suse.com/show_bug.cgi?id=1171596#c19
> Updating time sync disable note with xref (BSC#1171596)

- xml/deployment_cifs.xml
This patchset attempts to address https://github.com/SUSE/doc-ses/issues/244
- Split out Samba service restart instructions for standalone and HA deployments
- Add winbind HA instructions, needed for AD membership
> rework HA/standalone Samba service documentation

- xml/deployment_cifs.xml
"security = ADS" must be configured for winbind to function for AD
domain membership (bsc#1157369).
> Specify security and realm smb.conf parameters (bsc#1157369)

- xml/deployment_cifs.xml
"security = ADS" must be configured for winbind to function for AD
domain membership (bsc#1157369).
(cherry picked from commit 9cb51d0a75d737646e356eca45ca8857d09930da)
> deployment_smb: specify security and realm smb.conf parameters

- xml/admin_operating_monitor.xml
- xml/runtime_config.xml
This PR introduces new way of setting config options via a configuration database.
Rendered PDF is attached, section 19.1. & 19.2. are affected, the rest is not relevant now
[cha-ceph-configuration_color_en.pdf](https://github.com/SUSE/doc-ses/files/5122316/cha-ceph-configuration_color_en.pdf)
> Configuration database #458

- xml/admin_saltcluster.xml
This update adds an updated output of `ceph orch device ls` as a reference of 'MODEL' and 'VENDOR' strings
Closes #364
> Matching disk devices with drivegroups. Closes 364.

- xml/windows-ceph.xml
Adding https://beta.suse.com/private/SLE15/SP2/download/SES7/ceph4win/ the link where beta tester can download SES4Win.msi
BTW the entire doc use ceph.msi but the SES Team provides a SES4Win.msi. This need to be clarified.
> Adding link to SES4Win.msi

- xml/windows-appendix.xml
- xml/windows-ceph.xml
Also, remove the 'out' directory from samples conf files, to simplify installs for customers.
> Update name of installer (ceph.msi - SES4Win.msi)

- xml/admin_saltcluster.xml
"encryption:" tag in DriveGroups definition is wrong. "encrypted:" is correct.
> admin_saltcluster.xml: fix "encryption:" tag

- xml/admin_nfsganesha.xml
NFSv4 does not advertise exports via rpcbind/mountd. Instead these can
be enumerated by a client from the root of the pseudo NFSv4 filesystem
> admin_nfsganesha.xml: update to replace usage of `showmount`

- xml/deploy_cephadm.xml
If https://github.com/ceph/ceph-salt/pull/383 is merged, bootstrap minion will no longer be required to have the admin role.
> Bootstrap minion no longer required to have admin role

- xml/admin_nfsganesha.xml
DeepSea had the concept of `roles` to configure each ganesha daemon
according to pre-defined templates
Multiple cephadm NFS clusters should be be created as a replacement.
```
$ ceph orch apply nfs foo --pool nfs-ganesha --namespace foo
$ ceph orch apply nfs bar --pool nfs-ganesha --namespace bar
$ ceph orch apply nfs baz --pool nfs-ganesha --namespace baz
```
> admin_nfsganesha.xml: `roles` -> `clusters`

- xml/admin_ceph_upgrade.xml
NFS example in admin guide should reference `registry.suse.com` instead
of `registry.suse.de`
> rename `registry.suse.de` -> `registry.suse.com`

- xml/admin_saltcluster.xml
In the `ceph orch upgrade start` example we use a suse link. Lets use the same link in the status example.
> keep image link consistent is update section

- xml/deploy_caasp.xml
(e.g. a client configured with a kubeconfig file)
```
export KUBECONFIG=<path to the kubeconfig file>
```
> helm3 install should be run from a node with access to k8s

- xml/entity-decl.ent
We currently use the ceph-salt tool (meaning the commands are `ceph-salt BLAH` to deploy our Ceph cluster instead of the upstream `cephadm bootstrap`. I propose removing the mention of cephadm in the entities in favor of simply using `cephuser`. The `cephadm` command is used a total of once in the deployment guide, and I believe this is misleading. We don't want customers to confuse the options, and think they can operate the SES cluster with Ceph commands. If you use the upstream commands, you will get an upstream container instead, and the cluster will be unsupported.
> Proposing removal of cepham prompt to ceph

- xml/admin_ceph_upgrade.xml
- xml/manager_modules.xml
- xml/troubleshooting_caasp_debugging_rook.xml
This PR contains the following change:
It was an oversight to allow "empty" sections in GeekoDoc. To avoid validation issues in the future, this commit introduces
para/remark lines.
Also remove literal in screen as it is useless. ;)
> Add para/remark elements to avoid future problems

- xml/admin_rbd.xml
- xml/entity-decl.ent
Replaced neutral prompts with '@local', '@remote' suffixes for RBD mirroring content.
@trociny @denisok if you find another occurrence worth updating, make a list and let me know please
closes #677
> RBD mirror prompts fixed, minor fixes to text done (#677)

- xml/deploy_cephadm.xml
* extends the original section on RGW deployment using YAML specs
* created 2 subsections to better organize the flow
* rendered version attached (scroll down to section 5.4.3.4)
[deploy-cephadm-day2_color_en.pdf](https://github.com/SUSE/doc-ses/files/5364630/deploy-cephadm-day2_color_en.pdf)
> Added RGW specification for SSL access (bsc#1176677)

- .gitignore
- DC-ses-man
- convert-manpages.sh
- xml/art-storage-man.xml
- xml/ceph-volume.xml
- xml/ganesha-cache-config.xml
- xml/ganesha-ceph-config.xml
- xml/ganesha-config.xml
- xml/ganesha-core-config.xml
- xml/ganesha-export-config.xml
- xml/ganesha-log-config.xml
- xml/ganesha-rados-cluster-design.xml
- xml/ganesha-rados-grace.xml
- xml/ganesha-rgw-config.xml
- xslt/fix-manpages.xsl
This PR contains the following changes:
* a `convert-manpages.sh` script which downloads and converts all the RST files into DocBook.  Does the following steps:
1. Check if all necessary programs are installed. If not, show help text.
2. Clone the repository (or use the directory from last run).
3. Download additional manpages.
4. Remove any `:orphan:` lines from RST (this simplifies the conversion process).
5. Convert RST to DocBook5 with pandoc.
6. Fix the raw XML file from pandoc, write it to result directory.
* a `xslt/fix-manpages.xsl` XSLT stylesheets which corrects issues from the pandoc conversion
> Convert RST Manpages into DocBook

- ja/xml/admin_saltcluster.xml
[The procedure to recover a reinstalled OSD node](https://documentation.suse.com/ses/6/html/ses-all/storage-salt-cluster.html#ds-osd-recover) was updated with #472.
The present commit reflects this update to the Japanese document.
> Reflect #472 to JPN version

- xml/manager_modules.xml
This PR just contains the following small fix for SES6:
* Remove the `<literal>` inside a `<screen>`.
It's an unnecessary tag and isn't allowed in the upcoming GeekoDoc release. This makes it possible to stay compatible.
* No layout or further text changes.
> SES6: Remove literal in screen

- xml/deployment_iscsi.xml
In SLE15-SP2, the following features are now supported by kernel:
- 'RBD_FEATURE_OBJECT_MAP'
- 'RBD_FEATURE_FAST_DIFF'
- 'RBD_FEATURE_DEEP_FLATTEN',
This PR updates documentation accordingly.
Relates to: https://github.com/SUSE/ceph-iscsi/commit/a7b4d3884a6cc7b803ae6f086665da310359b011
> iscsi: Update list of RBD features supported by kernel

- xml/troubleshooting_caasp_debugging_rook.xml
That way, you don't have to edit the deployment manually but can just
execute the command and the deployment will be updated.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>
> troubleshooting_caasp_debugging_rook: Use set env for log level

- xml/admin_caasp_cephtoolbox.xml
The description and examples of the rook toolbox should be updated
with SUSE specific details.
> Update rook toolbox info with SUSE details

- xml/windows-appendix.xml
As reported by a user, the keyring file must contain a blank line
as the final line in the file. Update the comments and file contents
to reflect this.
> Add blank line to keyring sample

- xml/deployment_hwrecommend.xml
mds_cache_memory_limit defaults to 4GB
> Recommend 4GB as minimum MDS ram

- xml/admin_ceph_cephfs.xml
When decreasing the number of active MDS, deactivate is no longer needes. In fact to command no longer exists.
> remove deactivate step

- xml/admin_gui_dashboard.xml
- The PGs per OSD card on the "Dashboard" page is the average number.
- Change from `salt.purge runner` to `ceph-salt runner`.
- Need a space in `ceph mgr fail` command.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> Dashboard chapter minor fixes

- xml/windows-ses.xml
The upstream Dokany project is capitalized, so we should
use that in our docs as well.
> windows: Fix capitalization of Dokany

- xml/bp_troubleshooting_cephadm.xml
Add section to the cephadm troubleshooting guide on how to query the
list of default container images (BNC#1177102)
> Add section on querying the default container images

- xml/admin_rbd.xml
Closes #779
This is because this section has been superceded by: https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-day2-service-rbdmirror
> Remove outdated rbd-mirror-daemon section

- xml/admin_ceph_cephfs.xml
The name .snap being absent from a dir listing has confused users in the past.
> Add note regarding virtual .snap dir

- xml/manager_modules.xml
To get the balancer configuration the correct command should be `ceph balancer status` since what is returned with `ceph config-key dump` is much more than just the balancer configuration and is confusing if one is only looking for the balancer specific information.
> Update manager_modules.xml with proper command to get balancer configuration

- xml/admin_ceph_upgrade.xml
The command `zypper migrate` does not exist, `zypper migration` is correct.
> Fixing typo: "zypper migrate" -> "zypper migration"

- xml/deployment_cifs.xml
Performance and resource consumption benefits make CephFS kernel backed
shares desirable. Retain vfs_ceph instructions for legacy purposes.
(jsc#SES-2215).
> deployment_smb: recommend kernel backed shares

- xml/deploy_cephadm.xml
By default, the cephadm user can not execute ceph commands, it is configured to execute the commands using sudo via the "/etc/sudoers.d/ceph-salt" file.
> cephadm user needs sudo

- xml/admin_monitoring_alerting.xml
Add section about newly added GRAFANA_FRONTEND_API_URL to be able to
configure Grafana so that it can be reached when the Grafana users are
in a different DNS zone than the Ceph Dashboard back-end.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1176390
> SES6: Add docs about newly introduced GRAFANA_FRONTEND_API_URL setting

- xml/bp_troubleshooting_cephadm.xml
- xml/bp_troubleshooting_logging.xml
- xml/bp_troubleshooting_monitors.xml
closes #885 
rendered PDF is attached 
[book-storage-troubleshooting_color_en.pdf](https://github.com/SUSE/doc-ses/files/6034703/book-storage-troubleshooting_color_en.pdf)
See the new sections:
2.7 Per-service and per-daemon events
3.13 Disabling automatic deployment of daemons
6.4 Restoring the MONs quorum
6.8 Manually deploying a MGR daemon
> Updates to troubleshooting guide from upstream docs (#885)

- xml/admin_monitoring_alerting.xml
Add section about newly added GRAFANA_FRONTEND_API_URL to be able to
configure Grafana so that it can be reached when the Grafana users are
in a different DNS zone than the Ceph Dashboard back-end.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1176390
> SES7: Add docs about newly introduced GRAFANA_FRONTEND_API_URL setting

- xml/deploy_cephadm.xml
Previously the example was "nfs". I've changed it to "ganesha" for consistency with what DeepSea created in previous SES releases.
> Use 'ganesha' as example NFS namespace

- xml/admin_ceph_upgrade.xml
Recommends to restart salt-master and synchronize salt modules during upgrade
Closes bsc#1181092
> Syncing salt modules during upgrade (bsc#1181092)

- xml/admin_monitoring_alerting.xml
Related to updating the container version for Grafana shipped by default: https://github.com/SUSE/ceph/pull/429
> Update Grafana container tag version

- xml/admin_caasp_cephosd.xml
This important part was missing when removing/replacing OSDs on a rook-based Ceph-cluster
On host-based clusters, you may need to stop the Rook Operator while performing OSD removal steps in order to prevent Rook from detecting the old OSD and trying to re-create it before the disk is wiped or removed.
Signed-off-by: Stefan Haas <shaas@suse.com>
> doc: rook operator needs to get stoped on OSD removal

- xml/app_win_sample_conffile.xml
- xml/windows-ses.xml
Command line parameters have been transitioned to ceph.conf settings.
Update documentation and examples to reflect this.
Addresses #879 
> Update ceph-dokan uid/gid instructions

- xml/admin_ceph_upgrade.xml
Revise monitoring adoption section
- Add docs about how to set Node-Exporter image in cephadm for local registry.
- Be more clear about having to remove the Node-Exporter service from all nodes.
- Add a command to remove Node-Exporter from all nodes at once with Salt.
- Other text revisions.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181301
> Revise adoption of monitoring services

- README.adoc
Although I eventually found a reference to `daps-xmlformat` documented in the [Documentation Style Guide (at the end of chapter 8)](https:/documentation.suse.comstylecurrent), where the `README.adoc` is also pointing to, I can't help but wondering if it wouldn't be a little bit better to explicitly and briefly mention its existence directly in the `README.adoc`.
What do you think?
Fixes #901 
> highlight existence of formatting tool for contributors

- xml/admin_operating_pools.xml
The command currently is incorrect, in as such as it by default will attempt to migrate to the pool `rbd`, and since that pool in general does not exist anymore on clusters, using the command as it currently is documented will result in the following failure:
```
rbd: error opening default pool 'rbd'
Ensure that the default pool has been created or specify an alternate pool name.
```
It is thus required to in this case again specify the existing metadata pool and image as the target metadata pool/image and only specify the new data pool using the `--data-pool` option.
> Fix only migrate data to an EC Pool command

- xml/dashboard_user_cmdline.xml
The current management user commands mentions to simply specify the [PASSWORD] for the user, this will error out with for example:
`Error EINVAL: Please specify the file containing the password/secret with "-i" option.`
It is required to specify a password file containing the password using the -i option.
> Add missing -i option

- xml/admin_ceph_erasure.xml
Command syntax is incorrect for marking an EC pool as an RBD pool, the pool name needs to be specified before the application (we do seem to have this properly set elsewhere in the documentation), else (with the command as it is now in this part of the documentation) the following error will be returned since we then look for a pool name called `rbd` (which does by default not exist):
`Error ENOENT: unrecognized pool 'rbd'`
> Pool name should be specified first

- xml/admin_ceph_upgrade.xml
The command needs to include the zone else it will fail as follows:
'''
2021-09-24T21:10:40.291+0200 7f8ec8e14a40  1 Cannot find zone id= (name=), switching to local zonegroup configuration
2021-09-24T21:10:40.291+0200 7f8ec8e14a40 -1 Cannot find zone id= (name=)
2021-09-24T21:10:40.291+0200 7f8ec8e14a40  0 ERROR: failed to start notify service ((22) Invalid argument
2021-09-24T21:10:40.291+0200 7f8ec8e14a40  0 ERROR: failed to init services (ret=(22) Invalid argument)
'''
> Update user info command syntax

- xml/dashboard_manual_config.xml
The cert files should be present on the active MGR host, this information is specified since August in the online Ceph documentation (see https://docs.ceph.com/en/latest/mgr/dashboard/#enabling-single-sign-on-sso) but are not reflected currently in our documentation.
> Update Dashboard SSO information

- xml/admin_monitoring_alerting.xml
Revert update to Node-Exporter container. The issue that was tried to be solved by an update turned out to have been a mistake in merging. That way the correct version was replaced by an older one that was no longer available on registry.suse.com. This has been restored in https://github.com/SUSE/ceph/pull/445 to refer to Node-Exporter version 0.18.1. Naturally, the docs need to point to that version as well. Sorry for the fuss!
> Revert update of Node-Exporter from 1.0.1 to 0.18.1

- de/xml/MAIN.susestorage.xml
- es/xml/MAIN.susestorage.xml
- fr/xml/MAIN.susestorage.xml
- it/xml/MAIN.susestorage.xml
- ja/xml/MAIN.susestorage.xml
- pt_br/xml/MAIN.susestorage.xml
- zh_cn/xml/MAIN.susestorage.xml
- zh_tw/xml/MAIN.susestorage.xml
dm: tag cleaned-up  for all languages of SES 6.
Will be done for each branch version separately therefore no backports needed
> clean dm_tags ses6

- .gitignore
- xml/admin_ceph_upgrade.xml
- xml/admin_monitoring_alerting.xml
- xml/bp_troubleshooting_cephadm.xml
- xml/deploy_bootstrap.xml
In order to reflect changes in https://github.com/SUSE/ceph/pull/449
Prometheus server: ses/7/prometheus/prometheus-server:2.27.1
Node exporter: ses/7/prometheus/prometheus-node-exporter:1.1.2
Alertmanager: ses/7/prometheus/prometheus-alertmanager:0.21.0
> Update monitoring container images

- xml/admin_monitoring_alerting.xml
Adapt Prometheus Alertmanager SNMP Gateway setup to new upstream solution in SES7.1 (Pacific). This should give us less support effort.
@tbazant Please feel free to cherry-pick this PR/commit to add your changes in a separate PR.
Maybe it is possible to add those screenshots to the documentation, too.
> Adapt Prometheus Alertmanager SNMP documentation to new upstream solution

- xml/bp_troubleshooting_dashboard.xml
Activating the debug flag temporarily causes a HEALTH_WARN cluster state.
Signed-off-by: Volker Theile <vtheile@suse.com>
> Add a note to 'Debugging the Ceph Dashboard flag'

- xml/admin_ceph_upgrade.xml
- xml/admin_monitoring_alerting.xml
- xml/bp_troubleshooting_cephadm.xml
- xml/deploy_bootstrap.xml
> Update container image paths to point to `ceph` instead of `prometheus`

- xml/admin_ceph_upgrade.xml
- xml/deploy_core.xml
- xml/product-entities.ent
- xml/upgrade-to-pacific.xml
Hi @tbazant,
This is my proposal for bz#1197250.
There are 3 changes that cover 3 different scenarios when dealing with 7.1 and NFS mgr module:
1. clean installation of 7.1
2. upgrade from 6
3. upgrade from 7
For the 1. the modification is simply a normal step one must do after he completed the Ganesha service installation.
For cases 2. and 3. otherwise, this note has been rendered as an _Important_ box; this choice has been done to remark the fact that the upgrading process has actually broken something and you need to do an action to restore it.
I have also a note by @l-mb:
_This overlaps with bz#1197667 which is a section we can reference in the release notes then._
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>
> NFS Ganesha mgr module mandatory (re-)enable after installation/upgrade to Pacific

- xml/admin_ceph_gateway.xml
- More detailed instruction on par with the RedHat manual
- Include warning about consequences
Fixes: bsc#1198074
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>
> Rados Gateway: Update manual resharding procedure

- xml/admin_ceph_upgrade.xml
`rgw_frontend_ssl_key` is obsolete in SES 7.1, both SSL strings are now part of `rgw_frontend_ssl_certificate`
fixes https://bugzilla.suse.com/show_bug.cgi?id=1200319
> rgw_frontend_ssl_key is removed after upgrade to Pacific (bsc#0120319)

- xml/admin_ceph_upgrade.xml
- xml/upgrade-to-pacific.xml
- Changed format from Note to Important
- Information added also in upgrade-to-pacific.xml
Fixes: bsc#1200319
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>
> rgw_frontend_ssl_key is removed after upgrade to Pacific (bsc#1200319)

- xml/admin_ceph_upgrade.xml
Setting bluestore_fsck_quick_fix_on_mount true in 16.2.7 has been okayed by @tserong
> Revert "Removed dangerous option during upgrade (bsc#1200883)"
