SUSE/doc-ses

xml/admin_ceph_installation.xml

Pretty sure I got all of 'em ;-)

Tweaks to Crowbar install section

---

xml/admin_ceph_installation.xml

These docs are for SES 3.0 which is based upon SLES 12 SP1

Version fix

---

xml/admin_ceph_installation.xml

fixed paths of sls example files

---

xml/admin_about.xml

- some rewording
please port to development version as well.

SUSE:Maintenance:3605:124591

---

xml/admin_bestpractices_hwrecommend.xml
xml/admin_gui_oa.xml
xml/admin_install_salt.xml

Bug 1025404 - typo fixes from S:M:3828:127423
https://bugzilla.suse.com/show_bug.cgi?id=1025404

typo fixes

---

xml/admin_ceph_installation.xml

[docs] typos in crowbar's installation guide 
https://bugzilla.suse.com/show_bug.cgi?id=1025437

fixed typos in crowbar's installation

---

xml/admin_ceph_installation.xml
xml/admin_ceph_upgrade.xml
xml/deployment_cephfs.xml

* Included a section that points towards release notes
* Limitations for CephFS

Link RN and include general limitations (bsc#1028272)

---

xml/deployment_hwrecommend.xml

* Add Minimum Recommended Configuration to Documentation
* Clarifications of requirements vs. recommendations required

Hardware Requirements, bsc#1042283 & bsc#1029544

---

xml/admin_ceph_gateway.xml

HTTPS for RGW, FATE#323089

---

xml/admin_ceph_gateway.xml
xml/deployment_docupdates.xml

* Documented Sync Modules
* Metadata sync with Elasticsearch

RGW Sync Modules & Elasticsearch

---

xml/admin_ds_backup.xml
xml/deployment_additional_software_intro.xml
xml/deployment_rgw.xml

Signed-off-by: Mohamad Gebai <mgebai@suse.com>

Fix small nits in documentation

---

xml/admin_cifs.xml
xml/admin_docupdates.xml
xml/book_storage_admin.xml
xml/book_storage_deployment.xml
xml/deployment_cifs.xml
xml/deployment_ganesha.xml
xml/entity-decl.ent

* Samba supports vfs_ceph
* Samba failover with CTDB

CIFS export of CephFS

---

xml/admin_ceph_upgrade.xml

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1073277
Signed-off-by: Nathan Cutler <ncutler@suse.com>

Clarify that admin node should be upgraded first

---

xml/admin_ceph_troubleshooting.xml

Please verify if this change is correct.

Adjusting osd_id to reflect the correct syntax for this command

---

xml/admin_install_salt.xml
xml/deployment_docupdates.xml

* FQDN of all nodes must be resolvable to the public network IP
* BSC#1067113

Change 'Cluster Deployment'

---

xml/deployment_cephfs.xml

Signed-off-by: Jan Fajerski <jfajerski@suse.com>
Tried my best with regards to formatting. Feel free to edit/advise.

cephfs: add instructions about multi-mds cluster and update procedure

---

xml/deployment_cifs.xml

minor follow-up for bsc#1101478

---

xml/deployment_iscsi.xml

(cherry picked from commit b9c64e9fece49164e151dcfd9f54eb10cc56181a)

Document iSCSI gateway emulate_pr, bsc#1091405

---

xml/admin_install_salt.xml

Fix typo of OSD in documentation

Fix typo of OSD

---

xml/admin_ceph_cephfs.xml
xml/admin_ceph_iscsi.xml
xml/admin_operating_services.xml
xml/admin_rbd.xml
xml/deployment_iscsi.xml
xml/entity-decl.ent

This PR replaces `lrbd` with `ceph-iscsi`.

Replace lrbd with ceph-iscsi

---

xml/deployment_iscsi.xml

All RBD features are supported by tcmu-runner

---

xml/common_intro_feedback_i.xml

Signed-off-by: Laura Paduano <lpaduano@suse.com>

common_intro_feedback_i: removed word

---

xml/admin_rbd.xml

Fixes https://github.com/SUSE/doc-ses/pull/73

Striping is not a supported feature

---

xml/admin_gui_dashboard.xml

Signed-off-by: Laura Paduano <lpaduano@suse.com>

admin_gui_dashboard: rephrased some sentences

---

xml/admin_install_salt.xml

Signed-off-by: Laura Paduano <lpaduano@suse.com>

admin_install_salt: Rephrased sentence

---

xml/admin_gui_dashboard.xml

admin_gui_dashboard: fix some minor typos

---

xml/admin_ceph_iscsi.xml

Remove lrbd reference

---

xml/admin_gui_dashboard.xml

Signed-off-by: Stephan Müller <smueller@suse.com>

admin_gui_dashboard: Extended list handling and pools

---

xml/admin_gui_dashboard.xml

Signed-off-by: Stephan Müller <smueller@suse.com>

admin_gui_dashboard: Added missing IDs

---

xml/admin_install_salt.xml

The "Include the Salt minions..." line didn't make a lot of sense, so clarify that the deepsea_minions option has to be used here.

Target deepsea minions

---

xml/admin_ceph_tips.xml

After reviewing the earlier merge, a few fixes and adjustments need to be made.

Fix typos and clarify LED lights usage

---

xml/admin_nfsganesha.xml
xml/deployment_ganesha.xml

Signed-off-by: Ricardo Dias <rdias@suse.com>

NFS-Ganesha deployment and configuration update

---

xml/admin_ceph_upgrade.xml

Signed-off-by: Nathan Cutler <ncutler@suse.com>

admin_ceph_upgrade.xml: rewrite MON upgrade warning

---

xml/deployment_iscsi.xml

Map the RBD image to the iSCSI target

---

xml/admin_ceph_upgrade.xml

CTDB: upgrade follow-ups for bsc#1129108

---

xml/admin_install_salt.xml

* Mention firewalld (new in SLE15)
* Give example for how to set `DEV_ENV` in `global.yml`

Two updates for section 4.3

---

xml/admin_glossary.xml

Add 2 new terms to SES glossary (JSC#SES-876)

---

xml/admin_ds_backup.xml

Better wording and capitalization

---

xml/deployment_cephfs.xml

Addresses:
https://bugzilla.suse.com/show_bug.cgi?id=1135168
When approved, will backport to SES 5.5 dep guide as well.

Change "MDS nodes" to "MON nodes" in mount command (BSC#1135168)

---

xml/deployment_cephfs.xml

As of SES 6, cephFS quotes are supported. This PR changes that
language to add support and points to the admin guide.

Confirming cephFS quotes support for SES6 (BSC#1154269)

---

xml/admin_ceph_gateway.xml

Updating multi-site docs and adding new section
for updating the dashboard.

Multi-site docs update (BSC#1144717)

---

xml/entity-decl.ent

When cleaning the entity file, i introduced a version shift of SES and the underlying SLES. This PR fixes version numbers, returning them to original values.

Updated product and OS numbers for SES4 & SES5.5

---

ja/xml/contributors.xml

Replaced English snippets with Japanese ones in a sentence about Ceph contributors.

Included a Japanese translation about Ceph contributors (bsc#1154135)

---

xml/admin_ceph_upgrade.xml
xml/deployment_docupdates.xml

It is advisable to run `rpmconfigcheck` after each node upgrade to verify that no local changes
to  configuration files are lost.

Run 'rpmconfigcheck' after each node upgrade (jsc#SES-348)

---

xml/admin_install_salt.xml

Signed-off-by: Marcos Paulo de Souza <mpdesouza@suse.com>

admin_install_salt.xml: Update links related to lvm and raid

---

xml/deployment_hwrecommend.xml

Just improving the sentence, no content addition.

Re-worded minimum requirements for OSDs (bsc#1155931)

---

xml/deployment_ganesha.xml

Signed-off-by: Ricardo Dias <rdias@suse.com>

nfs-ganesha: improvements to the active-active deployment section

---

xml/admin_about.xml
xml/admin_ceph_upgrade.xml
xml/admin_install_salt.xml
xml/book_storage_deployment.xml
xml/containerized-kubernetes.xml
xml/deployment_admin_ha.xml
xml/deployment_cephfs.xml
xml/deployment_docupdates.xml
xml/deployment_ds_custom.xml
xml/deployment_ganesha.xml
xml/deployment_hwrecommend.xml
xml/deployment_iscsi.xml
xml/deployment_rgw.xml
xml/ses_glossary.xml

Finished the 2nd part of the proofing changes for the SES deployment guide.
Fixes issue JIRA #ses-1144

Incorporate all proofing notes into Deployment Guide

---

xml/admin_ceph_datamgm.xml

I found definitions of the terms here:
https://docs.ceph.com/docs/master/rados/operations/crush-map/
I found some standard geographical region abbreviations here:
https://www.seforall.org/sites/default/files/l/2013/09/5-gtf_overview.pdf
Using this info & lacking any other feedback, I have filled in the missing boxes.
Oxygen has helpfully reflowed the file for me -- I have attempted to correct this with DAPS-xmlformat.

Fill in values for "pod", "region" & "root" in bucket list. (BSC#1113055)

---

xml/admin_gui_dashboard.xml

These were missing for some reason, now their description is complete.

Added missing descriptions of Dashboard's performance widgets (bsc#1160971)

---

xml/ceph_maintenance_updates.xml

Fixes:
https://bugzilla.suse.com/show_bug.cgi?id=1161690
As requested by @Martin-Weiss

Added warning about adjusting pgp_num along with pg_num (BSC #1161690)

---

xml/deployment_hwrecommend.xml

Added a sentence to network recommendations that we do not support additional administration network.

Admin network not supported (bsc#1067112)

---

xml/admin_ds_backup.xml

I have taken the steps and commands from:
https://bugzilla.suse.com/show_bug.cgi?id=1134700
I have demoted the backup sect1 and sect2 material to sect2/sect3, allowing me to add a new sect1 with the restore material in.
This is quite minimal at present. I am sending a PR to elicit feedback.

1st draft of new Restore § to follow Backup §

---

xml/admin_ceph_upgrade.xml

Adding straw to straw2 verification step (BSC#1162242)

---

xml/admin_operating_services.xml
xml/deployment_hwrecommend.xml

This update describes detailed steps to shut down and start all nodes of the Ceph cluster.

Shutdown and starting of whole Ceph cluster (bsc#1126210)

---

xml/admin_operating_pools.xml

This update aligns an existing section on pool migration and prepends the subsections with general limitation of mentioned migration methods.

Added pool migration limitations (bsc#1140080)

---

xml/admin_ceph_gateway.xml
xml/entity-decl.ent

Rewritten the multi-site object gateway section to reflect updated upstream documentation.
PR initially by @theanalyst to remove oudated content. Finalised by @asettle

Update to the multisite gateway docs (BSC#1143769)

---

xml/deployment_cifs.xml

This update inserts information how to use RBD images together with SBD as a fencing device.

SMB gatways in SLE-HA setup enhancements (bsc#1123896)

---

xml/authors.xml

Nor Jana or Sven are authoring for SES 7, removing

Removing authors from SES 7

---

xml/admin_nfsganesha.xml
xml/entity-decl.ent

This update tells users how to view the configuration of Ganesha exports.

Getting Ganesha exports (bsc#1164497)

---

xml/deployment_ganesha.xml

Doc added in PR #151 has copy-paste issue. This PR fixes it, found by customer in BSC#1165745

Fixing portblock resource section (BSC#1165745)

---

xml/tuning-ceph-tuning.xml

tuning guide fixes for a couple of rgw config options

rgw tuning fixes

---

xml/deployment_cifs.xml

Fixes: https://github.com/SUSE/doc-ses/issues/223

deployment_smb: kernel backed share instructions

---

xml/deploy_cephadm.xml

Signed-off-by: Kai Wagner <kwagner@suse.com>

fixed missing prompt typo

---

xml/deploy_cephadm.xml

This update adds basic information about 'ceph orch' command + its full syntax to do a Ceph upgrade

Ceph upgrade instructions added

---

xml/deploy_cephadm.xml

Remove duplicate `ceph-salt config` text

---

xml/tuning-intro.xml

Updating product number for tuning guide

---

xml/admin_operating_monitor.xml

Minor change in command for SES7

Change 'mon_status' to 'mon stat' command (bsc#1165656)

---

xml/deploy_cephadm.xml

This cumulative update fixes flaws mwntioned in bsc#1169864, bsc#1169860, bsc#1169862 and improves the section about setting the time server.

Fixed time server section (bsc#1169864, bsc#1169860, bsc#1169862)

---

xml/tuning-os-tuning.xml

Adding more context to jumbo frames 

---

xml/tuning-ceph-tuning.xml

Adding link to MDS tuning section for OSDs - Closes #272

---

xml/deploy_cephadm.xml

This updated fixes several issues found by @swiftgist during testing round.

Update to the caphadm deployment (bsc#1169953)

---

xml/admin_ceph_cephfs.xml
xml/admin_ceph_iscsi.xml
xml/admin_ceph_upgrade.xml
xml/admin_gui_dashboard.xml
xml/admin_nfsganesha.xml
xml/admin_saltcluster.xml
xml/book_storage_deployment.xml
xml/deploy_cephadm.xml
xml/deployment_cifs.xml

This update adds a new section with a description on how to deploy OSDs with cephadm.
Although it also includes more files, only the 'xml/deploy_cephadm.xml' is relevant.
Moreover, i imported and updated the Drivegroups content, hope it's still valid

Deploying OSDs with cephadm

---

xml/deploy_cephadm.xml

Signed-off-by: Kai Wagner <kwagner@suse.com>

updated ceph-salt status output

---

xml/deploy_cephadm.xml

This update fixes unrelated fixes that apply to the cephadm deployment process.
It also fixes #295.

General fixes to cephadm deployment process

---

xml/ceph_maintenance_updates.xml

Adds entries for new Ceph point releases.
Closes #308

New sections for Ceph point releases (gh#SUSE/doc-ses#308)

---

xml/deploy_cephadm.xml

This update describes how to disable automatic packages update and nodes reboot.
Closes #294

Cluster update and reboot behavior (tbazant-reboots-gh#SUSE/doc-ses#294)

---

xml/tuning-appendix.xml
xml/tuning-os-tuning.xml

Adding CPU mitigations instructions to appendix

---

xml/deploy_caasp.xml
xml/deploy_cephadm.xml
xml/deploy_intro.xml

This update includes:
* several general doc updates/corrections
* deployment of MDS, RGW, and NFS services

Updates to SES7 deployment process

---

xml/book_storage_tuning.xml
xml/tuning-how.xml

Adding basics section to tuning guide into

---

xml/admin_ceph_tips.xml

Adding default customization for deepsea instruction

---

xml/deploy_cephadm.xml
xml/deploy_intro.xml

This update adds a small intro to cephadm.
Closes #324

Added introduction to cephadm (gh#SUSE/doc-ses#324)

---

xml/admin_ceph_cephfs.xml

Explictly mention the mons IP usage when mount cephfs

---

xml/runtime_config.xml
xml/tuning-ceph-tuning.xml

Adding OSD cache sizing docs

---

xml/deploy_cephadm.xml

This update explains use-cases for disabling automatic updates and reboots.
Closes #316

Disable updates and reboots (gh#SUSE/doc-ses#316)

---

xml/deploy_cephadm.xml

This update introduces multiple changes to the existing docs:
* adds a new section about service and placement specification
* updates and moves DriveGroups section
* updates services' deployment section to only apply YAML file specification
* removes CLI placement specifications
Closes #325 
Closes #305 
Closes #340 
Closes #345 
Closes #347

Introduces YAML services/placement specification and removes the CLI one (gh#325)

---

xml/admin_ceph_upgrade.xml

1. Add msgr2 enablement to Upgrade section
2. Add new final steps section for SES 5 -> 6 upgrade
Closes #314
Closes #315

Adding new final steps section and updating OSD upgrades

---

xml/deploy_cephadm.xml

This update makes NFS deployment a little more descriptive
closes #352

Extend NFS deployment section (gh#352)

---

xml/deploy_cephadm.xml

Improves RGW deployment via cephadm's spec file
Closes #368

Added zone and realm to OGW deployment (gh#368)

---

xml/admin_install_salt.xml
xml/deployment_cephfs.xml

Related to: https://github.com/ceph/ceph/pull/35628

Replace "whitelist" and "blacklist" language

---

xml/admin_ceph_gateway.xml
xml/admin_operating_monitor.xml
xml/admin_saltcluster.xml
xml/common_intro_available_doc_i.xml
xml/deploy_cephadm.xml
xml/runtime_config.xml
xml/tuning-ceph-tiered-storage.xml
xml/tuning-lvmcache.xml

This reverts commit 3085fa281a7e8316a77df90164e9443ab471f9fc.
https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt

Revert "Revert "Merge branch 'master' of github.com:SUSE/doc-ses""

---

xml/common_intro_available_doc_i.xml

Waiting on Security to be written. Closes #356

Adding introductions for tuning and troubleshooting

---

xml/deploy_cephadm.xml

Adding missing additional invocation

---

xml/admin_about.xml
xml/admin_ceph_upgrade.xml
xml/admin_cephx.xml
xml/admin_install_salt.xml
xml/admin_nfsganesha.xml
xml/admin_operating_pools.xml
xml/admin_rbd.xml
xml/admin_saltcluster.xml
xml/bp_troubleshooting_objectgateway.xml
xml/deploy_cephadm.xml
xml/deployment_additional_software_intro.xml
xml/deployment_ganesha.xml
xml/deployment_hwrecommend.xml
xml/tuning-ceph-tiered-storage.xml
xml/tuning-ceph-tuning.xml

Changing &rgw; to &ogw;

---

xml/deploy_cephadm.xml

Multiple updates to the cephadm deployment procedure

---

xml/admin_install_salt.xml

LTSS repos break migration to SES6

No need for LTSS repositories (bsc#1173306)

---

xml/admin_ceph_upgrade.xml

LTSS repos break migration form SES5

Remove LTSS repositories before migration (bsc#1173306)

---

xml/deploy_cephadm.xml

Added a reference to SLE container registry section (gh#383)

---

xml/admin_saltcluster.xml

This updates adds a useful informaiton to the procedure of removing OSDs.
It also makes the host/node terminology more accurate.
Closes #420

Note to removing OSDs (gh#420)

---

xml/deploy_cephadm.xml

Fixed cluster YAML indentation (gh#442)

---

xml/admin_operating_services.xml
xml/bp_troubleshooting_tips.xml

Updated operating Ceph services to not use DeepSea anymore (gh#366)

---

xml/deploy_cephadm.xml

Export cluster specification (gh#367)

---

DC-ceph-windows
DC-ses-admin
xml/MAIN.susestorage.xml
xml/authors-windows.xml
xml/book-ceph-windows.xml
xml/windows-appendix.xml
xml/windows-ceph.xml

This was written by Mike Latimer and is released for a technical preview as a standalone guide.

Adding new Ceph for Windows guide in XML format

---

xml/admin_saltcluster.xml

Updating procedure to ensure OSDs are up - Closes#468

---

xml/deploy_cephadm.xml

This update adds a section on how to deploy the monitoring stack in SES7
Closes #441

Monitoring stack deployment

---

xml/deploy_cephadm.xml

Removed `system_update` option from ceph-salt. Closes #492

---

xml/admin_saltcluster.xml

Updating service names to more appropriate syntax

---

xml/admin_saltcluster.xml

Adding missing command syntax to upgrade

---

xml/admin_saltcluster.xml

Adding note regarding renaming admin node

---

xml/admin_gui_dashboard.xml
xml/bp_troubleshooting_tips.xml

Also fixes syntax for "system" tag

Updating firewall settings and linking to relevant sections - Closes#522

---

xml/common_intro_feedback_i.xml

Replacing the usual feedback channel by the public beta channels for now!

Adding public beta channels

---

xml/admin_ceph_gateway.xml
xml/admin_rbd.xml
xml/bp_troubleshooting_objectgateway.xml
xml/bp_troubleshooting_osds.xml
xml/bp_troubleshooting_status.xml
xml/bp_troubleshooting_tips.xml

Changing systemd command sets

---

xml/bp_troubleshooting_status.xml

Adding health checks for cephadm into troubleshooting statuses

---

xml/deploy_cephadm.xml

Day 2 Dashboard deployment commented out (#568)

---

xml/deploy_cephadm.xml

Explained network IP / subnet mask (#560)

---

xml/bp_troubleshooting_cephadm.xml

1. Adding manual mgr deploy instructions
2. Adding PTF instructions for SES
Closes #399
Closes #493

Adding new sections to troubleshooting cephadm

---

xml/bp_troubleshooting_tips.xml

Adding new net runner docs from Eric

---

xml/deploy_cephadm.xml

Adding tuned profile instructions

---

xml/bp_troubleshooting_osds.xml

Signed-off-by: Joshua Schmid <jschmid@suse.de>

Review troubleshooting OSDs

---

xml/admin_saltcluster.xml

Fixing command for removing nodes from salt cluster

---

xml/bp_troubleshooting_objectgateway.xml
xml/bp_troubleshooting_tips.xml

Updating and replacing OGW troubleshooting chap

---

xml/admin_ceph_cephfs.xml

Updating cephfs deploy link in admin guide

---

xml/admin_saltcluster.xml

Fixed referring to section about adding new minions (#557)

---

xml/bp_troubleshooting_cephfs.xml
xml/bp_troubleshooting_logging.xml

Updating cephfs docs

---

xml/bp_troubleshooting_tips.xml
xml/deploy_cephadm.xml

* merged @asettle 's recent changes
* 2 comments remain and need to be reviewed

Hints and tips, suspicious snippets

---

xml/admin_operating_services.xml

Updating ceph cluster shutdown commands

---

xml/bp_troubleshooting_nfs.xml

another round of clean-up ... 

Clean-up NFS debug logging and user defined port sections

---

xml/admin_ceph_cephfs.xml

Updating ceph mds rank command from obsolete version

---

xml/ceph_maintenance_updates.xml

Adding upstream point release docs

---

xml/deploy_cephadm.xml

Also need to further update the documentation to reflect previous iterations: https://susedoc.github.io/doc-ses/ses6/single-html/ses-deployment/#cha-ceph-as-iscsi

Adding igw install instructions

---

DC-ses-rook
xml/admin_caasp_intro.xml
xml/book_storage_rook.xml
xml/deploy_caasp.xml
xml/troubleshooting_caasp_debugging_rook.xml

Updating deployment information for helm

---

xml/book_storage_deployment.xml
xml/deploy_cephadm.xml
xml/deployment_iscsi.xml

This PR also contains a placeholder for information on what
IP addresses to apply.
This PR should also have in scope further information on
ceph-iscsi and how to operate with cephadm.

Updating ceph-iscsi docs and deployment

---

xml/windows-appendix.xml
xml/windows-ses.xml

Due to an executable being renamed (rbd-nbd.exe), the Windows driver documentation needs to be updated. In addition to this change, fix a few additional content issues.

[win] Update documentation for Beta2

---

xml/bp_troubleshooting_cephfs.xml

Signed-off-by: Luis Henriques <lhenriques@suse.de>

Added section on using legacy kernel clients

---

xml/admin_caasp_crd.xml

Included reference to DriveGroups (#548)

---

xml/deploy_cephadm.xml

Remove duplicated word `you`

---

xml/bp_troubleshooting_tips.xml

This is a first stab to outline the procedure. I'll come back with more detailed instructions and a few shell snippets.

Update troubleshooting tips about orphaned partitions

---

xml/deploy_cephadm.xml

Remove optional <placement_string> parameter

---

xml/ceph_prompts.xml
xml/deploy_cephadm.xml
xml/deployment_hwrecommend.xml

1. Update title of minimum config chap
2. Add final steps section (extra for networking)
3. Added note about the ceph-salt config command
4. Updated the ceph prompts for salt
Closes #663, #662, #661, #659

Editing deployment file

---

xml/admin_ceph_upgrade.xml
xml/entity-decl.ent

Included all instructions from High Level Steps in https://confluence.suse.com/pages/viewpage.action?pageId=506822934
Rendered version attached
[cha-ceph-upgrade_color_en.pdf](https://github.com/SUSE/doc-ses/files/5340916/cha-ceph-upgrade_color_en.pdf)

Up-to-date SES6 > 7 upgrade procedure

---

xml/admin_gui_dashboard.xml
xml/admin_rbd.xml
xml/entity-decl.ent

Fixing multiple RBD mirror issues (#346)

---

xml/admin_rbd.xml

Added keyring of the same name as remote config file (#653)

---

xml/deploy_cephadm.xml

Container registry systemd unit  file (#513)

---

xml/admin_ceph_erasure.xml
xml/admin_operating_monitor.xml
xml/admin_operating_pools.xml
xml/admin_saltcluster.xml
xml/common_intro_available_doc_i.xml
xml/runtime_config.xml

Adding missing service ID and ceph apply command

---

xml/admin_ceph_upgrade.xml

* rendered version attached
* closes #692 
[upgrade-gateways_color_en.pdf](https://github.com/SUSE/doc-ses/files/5377425/upgrade-gateways_color_en.pdf)

RGW upgrade procedure (jsc#SES-1885)

---

xml/admin_saltcluster.xml

* better structured ways to disable the managed OSD mode

Improved unmanaged OSD mode (bsc#1177199)

---

xml/admin_ceph_upgrade.xml

Clarifying prereqs for before upgrading

---

xml/bp_troubleshooting_tips.xml
xml/deploy_cephadm.xml

Adding instructions about dense nodes (BSC#1177776)

---

xml/deploy_cephadm.xml

~~**After https://github.com/ceph/ceph-salt/pull/439 is merged.**~~
---
Adapt docs according to https://github.com/ceph/ceph-salt/pull/439

timeserver: Add instead of set, and rename config node

---

xml/common_intro_rook.xml
xml/rook_prompts.xml

1. Removed Ceph-specific content for this guide
2. Adds new file for rook prompts
Closes #708

Adding new rook commands file

---

xml/book_storage_troubleshooting.xml

Currently there is no troubleshooting-iscsi chap ready for SES 7.

Commenting out iscsi chap - no content at present

---

xml/admin_saltcluster.xml
xml/bp_troubleshooting_tips.xml

1. Renames chap to adding smaster node to new node
2. Updates procedure to include clearer steps
3. Adds troubleshooting chapter

Adding admin node to new server update (BSC#1176326)

---

xml/ceph_maintenance_updates.xml

Updating point releases for SES 6

---

xml/admin_rbd.xml
xml/deploy_cephadm.xml
xml/entity-decl.ent

* included rbd-mirror YAML specs for deployment
* removed section about manual adding rbd-mirror peer
closes #642

RBD mirror deployment specification included (bsc#1177308)

---

xml/admin_monitoring_alerting.xml
xml/deploy_cephadm.xml

Add explanation to customize monitoring images

---

xml/admin_ceph_upgrade.xml
xml/admin_monitoring_alerting.xml
xml/deploy_cephadm.xml

Consolidated Monitoring Stack deployment (#727)

---

xml/admin_ceph_upgrade.xml

Minor fixes to the upgrade chapter (#729#731)

---

xml/admin_install_salt.xml

This PR also requires the examples to be fixed, TBD

Adding DriveGroups note (BSC#1162534)

---

xml/admin_saltcluster.xml

Updating --dry-run command instruction

---

xml/deployment_hwrecommend.xml

deployment: use consistent minimum and recommended resource values

---

xml/admin_ceph_cephfs.xml

Remove mds_standby_for_rank

---

xml/admin_gui_dashboard.xml

Removing dupliated read/write option from dashboard

---

xml/admin_rbd.xml

Improving description and procedure for EC pools

---

xml/windows-ses.xml

The Windows driver is still being offered as a tech preview. Add
a section to clarify this status.

windows: add tech preview section

---

xml/admin_saltcluster.xml

Adding extra update step to ensure cephadm is updated on all nodes

---

xml/common_intro_available_doc.xml

Updating common file to contain active URLs

---

xml/admin_rbd.xml

Updating rbd command list to reflect upstream

---

xml/bp_troubleshooting_dashboard.xml

bp_troubleshooting_dashboard: Add two missing pieces

---

xml/admin_rbd.xml

Adding important note on iscsi support

---

xml/deploy_cephadm.xml
xml/product-entities.ent

Fixed salt log level setting (#788)

---

xml/admin_operating_services.xml

The syntax is used throughout the documentation, therefore i consider it valid
cloes #723

 Restarting whole service type (#723)

---

xml/common_intro_available_doc.xml

Improved note about docs on the file system (#766)

---

xml/deploy_cephadm.xml

Adding private registry tip

---

xml/manager_modules.xml

Removing note - we fully support the upmap balancer in SES7

---

xml/bp_troubleshooting_osds.xml

Removing indepth section and replacing with support info

---

xml/admin_ceph_gateway.xml

Closes #744 
Requires forward-port to SES 7

Adding final step to SSL config for RGW

---

xml/bp_troubleshooting_cephadm.xml

Distributing PTF and software updates (#754)

---

xml/admin_saltcluster.xml

Adding crush removal step

---

xml/admin_saltcluster.xml

NOTE: only lines 1092-1096 are relevant, the rest is XML formatting
closes #819

Updated output of 'ceph orch ps' command (#819)

---

xml/admin_install_salt.xml

Added note about nodes with multiple networks (bsc#1178791)

---

xml/deploy_cephadm.xml

Adding unsupported note for msgr2

---

xml/deploy_cephadm.xml

Adding note with a link to pool instructions

---

hooks/pre-commit
xml/deploy_cephadm.xml

Updated output of device listing (#820)

---

xml/admin_monitoring_alerting.xml

Fix Alertmanager configuration example

---

xml/ses_glossary.xml

XML formatting file: ses_glossary.xml ... successful

Updating the SES glossary

---

xml/manager_modules.xml

Provide proper command and describe its output more accurately.

Get proper balancer status information

---

xml/admin_ceph_upgrade.xml

Adding instructions on removing LTSS packages

---

xml/deploy_cephadm.xml

Added 'mon_ip' configuration (#818)

---

xml/deploy_cephadm.xml

the output was already fixed in earlier issue
closes #840

Removed the call for 'ceph-volume' (#840)

---

xml/admin_ceph_upgrade.xml
xml/admin_install_salt.xml

Relevant lines are 330-357, rest is XML formatting
Closes bsc#1162543

Moving scrub-related options to [global] section (bsc#1162543)

---

xml/admin_ceph_upgrade.xml

Restart salt master and sync salt modules (#850)

---

xml/admin_ceph_upgrade.xml

Re-added and extended the post-upgrade clean-up steps

---

xml/admin_monitoring_alerting.xml

Removed cmdline deployment of the monitoring stack (861)

---

xml/admin_ceph_upgrade.xml

Added missing hyphen to compat cmd (#873)

---

xml/admin_ceph_upgrade.xml

Replaced HOSTNAME with MINION_ID (#866)

---

xml/admin_ceph_upgrade.xml

Apply RGW specification before restartinthe gatewayit (#864)

---

xml/admin_ceph_upgrade.xml

Mention SES6 release notes instead of general speech (#863)

---

xml/admin_ceph_upgrade.xml
xml/deploy_cephadm.xml

Added a section about local registry credentials (#868)

---

xml/admin_ceph_upgrade.xml

Removed insecure registry (#867)

---

xml/deploy_caasp.xml

Replaced placeholder with a specific REPO_URL (#855)

---

xml/admin_ceph_datamgm.xml
xml/admin_operating_monitor.xml
xml/admin_operating_pools.xml
xml/bp_troubleshooting_status.xml
xml/deployment_cifs.xml

Removed unnecessary  'PG_NUM' option (#848)

---

xml/admin_ceph_upgrade.xml

Fixes: https://github.com/SUSE/doc-ses/issues/872

Add more detail to Upgrading NFS Ganesha section

---

xml/admin_ceph_upgrade.xml

Add more detail to Upgrading the Object Gateway section

---

xml/admin_ceph_upgrade.xml
xml/deploy_cephadm.xml

closes #871 
closes #892 
closes #893 
closes #894 
closes #895
closes #896

Fine tuning of the upgrade process (bsc#1181664)

---

xml/admin_monitoring_alerting.xml

Adding section about how to update monitoring services once the locations to container images have been updated.

admin/monitoring: Add section: updating monitoring services

---

xml/deployment_hwrecommend.xml

closes https://bugzilla.suse.com/show_bug.cgi?id=1181369

Updated DB volume requirements (bsc#1181369)

---

xml/admin_operating_monitor.xml
xml/bp_troubleshooting_logging.xml
xml/runtime_config.xml

Closes https://bugzilla.suse.com/show_bug.cgi?id=1181488

Fixed 'ceph daemon' commands (bsc#1181488)

---

xml/ceph_maintenance_updates.xml

Added all recent Ceph maintenance updates (#910)

---

xml/ceph_maintenance_updates.xml

Added maintenance updates up to 15.2.10 (#911)

---

xml/admin_ceph_gateway.xml

Added rgw_s3_auth_use_ldap option description (#909)

---

xml/admin_saltcluster.xml

doc: adding addendum deep scrub

---

xml/admin_install_salt.xml

Use 'ceph-volume' do zap disk before OSD deployment (bsc#1171887)

---

xml/admin_ceph_upgrade.xml

Related to https://github.com/SUSE/doc-ses/pull/920

Update remnant of previous Grafana version

---

xml/admin_ceph_upgrade.xml
xml/ceph_maintenance_updates.xml
xml/deploy_cephadm.xml
xml/product-entities.ent

Info about health warning coming with the new Ceph point release

---

xml/admin_nfsganesha.xml

This update improves the understand of what the Ganesha service does not and how to manually create an NFS export
Closes #767  
Closes #765

Operating NFS service,  manual NFS export

---

xml/admin_ceph_upgrade.xml

Included SAMBA GW in the upgrade process (#862)

---

xml/admin_ceph_gateway.xml

Based on the new changes from https://github.com/ceph/ceph/pull/41380 .
Resolves BSC#1183978
Signed-off-by: Stephan Müller <smueller@suse.com>

Improve RGW multisite

---

xml/admin_ceph_datamgm.xml

Fixed typo (#964)

---

xml/admin_monitoring_alerting.xml

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1192875

Update Node-Exporter version

---

xml/dashboard_manual_config.xml

closes https://bugzilla.suse.com/show_bug.cgi?id=1192317

Fixed commands generating dashboard certificates (bsc#1192317)

---

xml/bp_troubleshooting_cephadm.xml

closes bsc#1193293
rendered PDF is attached 
[bp-troubleshooting-cephadm_color_en.pdf](https://github.com/SUSE/doc-ses/files/7668494/bp-troubleshooting-cephadm_color_en.pdf)

Fixed PTF process (bsc#1193293)

---

xml/deploy_bootstrap.xml

Closes https://bugzilla.suse.com/show_bug.cgi?id=1196042

Added flag for container image deletion (bsc#1196042)

---

xml/deploy_bootstrap.xml

Closes https://bugzilla.suse.com/show_bug.cgi?id=1196043

Added link to SLE registry info (bsc#1196043)

---

xml/admin_caasp_cluster.xml
xml/book_storage_rook.xml

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1191535
rendered PDF is attached 
[admin-caasp-cluster_color_en.pdf](https://github.com/SUSE/doc-ses/files/8025175/admin-caasp-cluster_color_en.pdf)

Added new chapter/section on cluster shutdown (bsc#1191535)

---

xml/admin_monitoring_alerting.xml

Fixed alertmanager specification for Ceph orchestration

---

xml/admin_monitoring_alerting.xml

Restart MGR after configuring grafana certs (#990)

---

xml/bp_troubleshooting_dashboard.xml

Signed-off-by: Volker Theile <vtheile@suse.com>

Adding exceptions for self-signed SSL certificates in the Ceph Dashboard

---

xml/dashboard_manual_config.xml

Updated commands for setting OGW credentials

---

README.adoc

Update SUSE doc toolchain install URL

---

xml/admin_ceph_upgrade.xml

Minor updates to SES 6 -> 7.1 upgrade procedure

---

xml/admin_ceph_upgrade.xml

closes #1003 
PDF is attached
[upgrade-mon-mgr-nodes_color_en.pdf](https://github.com/SUSE/doc-ses/files/8322857/upgrade-mon-mgr-nodes_color_en.pdf)

Added 1 step to OSD 6 > 7.1 upgrade procedure for format conversion

---

doc-kit.conf
xml/common_intro_feedback.xml
xml/common_intro_support.xml
xml/deploy_core.xml
xml/generic-entities.ent

fixes https://bugzilla.suse.com/show_bug.cgi?id=1196038
PDF is attached
[deploy-cephadm-day2-services_color_en.pdf](https://github.com/SUSE/doc-ses/files/8324923/deploy-cephadm-day2-services_color_en.pdf)
!!!see the inline comments for different SES 7 backporting!!!

OGW configured for both ports (bsc#1196038)

---

xml/deploy_caasp.xml

Some minor fixes relating to helm >= 3.7.

Helm fixes

---

xml/bp_troubleshooting_cephadm.xml

- Add ingress images to list of possible container images
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

cephadm: complete list of container images

---

xml/upgrade-to-pacific.xml

Note about how remove unused images (bsc#1198654)

---

xml/admin_ceph_gateway.xml
xml/admin_ceph_iscsi.xml
xml/admin_ceph_kvm.xml
xml/admin_ceph_tips.xml
xml/admin_ceph_troubleshooting.xml
xml/admin_ceph_upgrade.xml
xml/admin_docupdates.xml
xml/admin_install_salt.xml
xml/admin_saltcluster.xml
xml/deployment_admin_ha.xml
xml/deployment_cifs.xml
xml/deployment_docupdates.xml
xml/tuning-appendix.xml

2 links about `distribution management system` are not updated yet, i can't find multi-html equivalent

Cancel single HTML links

---

xml/admin_ceph_upgrade.xml
xml/deploy_core.xml
xml/deploy_intro.xml
xml/upgrade-to-pacific.xml

Closes: bsc#1198656, bsc#1197667, bsc#1198930, bsc#1198905

Updating 7.1 documentation

---

xml/deployment_cephfs.xml

fixes #989 and jsc#DOCTEAM-646

Removed MDS deactivation from a procedure (jsc#DOCTEAM-646)

---

xml/deploy_additional.xml

Reported wrong RBD image size

---

xml/deploy_core.xml

Rephrased sentences to match new reality

---

xml/admin_ceph_upgrade.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1196334

Re-run login to a custom registry (bsc#1196334)

---

xml/admin_ceph_upgrade.xml

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1200883

Removed dangerous option during upgrade (bsc#1200883)

---

xml/upgrade-to-pacific.xml

Upgrading monitoring services (jsc#1030)

---

xml/admin_ceph_upgrade.xml
xml/deploy_bootstrap.xml

Signed-off-by: Alexandra Settle <asettle@suse.com>

Updating container image sections (BSC#1201389, 1201388)

---

xml/bp_troubleshooting_logging.xml

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1181668

Attaching GDB to a failing process (bsc#1181668)

---

xml/admin_ceph_upgrade.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1201472

Added after-upgrade step to check for osdspec_affinity (bsc#1201472)

---

xml/admin_ceph_upgrade.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1202068

Added command to pull images from the default registry (bsc#122068)

---

xml/admin_saltcluster.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1202048

Added steps to migrate to new DB device (bsc#1202048)

---

xml/admin_saltcluster.xml

Added section on examining offline containers

---

xml/admin_ceph_upgrade.xml

Updated non-functional link to the backup chapter

---

xml/admin_saltcluster.xml

Switched order of steps when removing a node.

---

xml/deploy_bootstrap.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1204809

Added no_proxy option for direct container communication (bsc#1204809)

---

xml/MAIN.susestorage.xml
xml/book_storage_admin.xml
xml/book_storage_deployment.xml
xml/book_storage_rook.xml
xml/book_storage_security.xml
xml/book_storage_troubleshooting.xml
xml/book_storage_windows.xml
xml/product-entities.ent

Introduce `&productnameshort;` entity as discussed in SLE Writers Call on 2022-11-21.
Tomas, if you are okay with the change, I will take care of cherry-picking it into the different branches.
* DOCTEAM-828
- SES

Introduce &productnameshort; entity

---

xml/bp_troubleshooting_tips.xml

Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1204438

Fixup `network.*` runner commands

---

xml/admin_ceph_upgrade.xml

Stop and start sanity checks during upgrade

---

xml/admin_saltcluster.xml
xml/deploy_core.xml

Refreshing SSL certificates

---

xml/admin_saltcluster.xml

BACKPORT: Clarifying migrate DB commands (BSC#1211729)

---

xml/MAIN.susestorage.xml
xml/art-storage-man.xml
xml/book_storage_admin.xml
xml/book_storage_deployment.xml
xml/book_storage_rook.xml
xml/book_storage_security.xml
xml/book_storage_troubleshooting.xml
xml/book_storage_windows.xml

* Change version attribute to "5.2"
* Add `<meta name="series">`
* Add `<meta name="task">` (sometimes disabled)
* Add the ITS namespace in root element

Add metadata for SES in book  & article files
